authors = ["Andy Ferris <ferris.andy@gmail.com>"]
name = "AcceleratedArrays"
uuid = "44e12807-9a19-5591-91cf-c1b4fb89ce64"
version = "0.2.2"

[deps]
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
